# Generated by Django 3.1.5 on 2021-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
