# Generated by Django 3.1.5 on 2021-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='f697c270', max_length=100),
        ),
    ]
