# Generated by Django 3.1.5 on 2021-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210209_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='amount',
            field=models.CharField(default='500', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ac5c45a4', max_length=100),
        ),
    ]
