# Generated by Django 3.1.5 on 2021-02-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210209_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(default='Kg', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='eb1c420a', max_length=100),
        ),
    ]
